name: Ёврика Musica
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff167d35-4c00-40a7-acb6-9702dd5295e3.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3f0bdab-d15d-4856-9c7f-a98e9d404307.jpg
layout_spectrum: 0.3432505701355968
typography_spectrum: 0.20132938603972
analytics:
  facebook: '1040561646063240'
  google: UA-85051577-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8040018069235111
  lightness: 0.4885073856701429
  saturation: 0.1865547802835924
  rhythmicContrast: 0.2233101006457121
title: "Ёврика Musica. Сайт Петра Талалая \uD83C\uDFB6 \uD83D\uDCAA "
description: Живое музыкальное искусство - жителям большого города!
author:
  name: Piotr Talalay
  url: 'http://priot.ru'
  email: talalife@gmail.com
content_rating:
  adult: false
navigation:
  - name: Angel Ontalva VS Priot Duo
    id: 424a3141-ecac-4951-9cc4-7a174932950c
    type: content
  - name: Open Trio / Open Quartet
    id: 65a7cf23-9f10-4df3-a740-4aca23ed235e
    type: content
  - name: Seven Eight Band
    id: 86da30e0-0fda-4392-af20-db9cc41552b0
    type: content
  - name: Tinto Brass Band
    url: 'http://tintobrassband.ru'
    type: external
  - name: Календарь
    id: 76e560cf-b135-4ec0-a831-145cc4d64165
    type: content
  - name: Воодушевляющее Прослушивание
    url: 'http://upliftinglistening.youreka.ru'
    type: external
  - name: Биография Талалая
    id: c6a0dbeb-2d25-40a2-8328-a1f87289552a
    type: content
  - name: Curriculum Vitae Талалая
    id: c6a0dbeb-2d25-40a2-8328-a1f87289552a
    type: content
  - name: Райдер Талалая
    id: fd23009f-2323-4d89-8775-b9d3bbfb46f0
    type: content
content: []
github: true
